sudo: required
dist: xenial
language: python
cache: pip
python:
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-coverage
script:
  - pytest --cov-config .coveragerc --cov=rest_client_gen -m "not no_expected" test/
after_success:
  - coveralls
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev