sudo: required
dist: xenial
language: python
cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov requests coveralls
script:
  - pytest --cov-config .coveragerc --cov=rest_client_gen -m "not no_expected" test/
after_success:
  - coveralls
matrix:
  include:
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8-dev