sudo: required
dist: xenial
language: python
cache: pip
install:
  - python setup.py install
  - pip install pytest pytest-cov requests coveralls codacy-coverage
script:
  - python setup.py test -a '--cov-config .coveragerc --cov=json_to_models -m "not no_expected" test/'
after_success:
  - coverage xml
  - coveralls
  - python-codacy-coverage -r coverage.xml
matrix:
  include:
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8-dev